# Generated by Django 3.1.3 on 2020-12-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Длина изделия'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(max_length=50, null=True, verbose_name='Материал изделия'),
        ),
    ]
